language: ruby
rvm: '2.5.0'

env:
  global:
    - CC_TEST_REPORTER_ID=db09d2552461d82b23a168446d7e58a16becee7853eb51398769f49caa4b5c5a

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
